// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcIFpwj0v4pNRXtIRauwgir7PZBexWAww',
    appId: '1:861413051748:web:35585515ebfee6c038fe71',
    messagingSenderId: '861413051748',
    projectId: 'chatapp-86008',
    authDomain: 'chatapp-86008.firebaseapp.com',
    storageBucket: 'chatapp-86008.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LoYnQyaj-PZpe2XKdnnqowUWJsY_9hk',
    appId: '1:861413051748:android:8cf968905080fc3938fe71',
    messagingSenderId: '861413051748',
    projectId: 'chatapp-86008',
    storageBucket: 'chatapp-86008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6j-dFHtW9rW3B7GxRklev3Jk6eoVD4Q',
    appId: '1:861413051748:ios:afa21eff8c95b17e38fe71',
    messagingSenderId: '861413051748',
    projectId: 'chatapp-86008',
    storageBucket: 'chatapp-86008.firebasestorage.app',
    iosClientId: '861413051748-jnk0b9mtn83rlb30qmp4ni26egj2jng8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6j-dFHtW9rW3B7GxRklev3Jk6eoVD4Q',
    appId: '1:861413051748:ios:afa21eff8c95b17e38fe71',
    messagingSenderId: '861413051748',
    projectId: 'chatapp-86008',
    storageBucket: 'chatapp-86008.firebasestorage.app',
    iosClientId: '861413051748-jnk0b9mtn83rlb30qmp4ni26egj2jng8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcIFpwj0v4pNRXtIRauwgir7PZBexWAww',
    appId: '1:861413051748:web:8a9615561d33073438fe71',
    messagingSenderId: '861413051748',
    projectId: 'chatapp-86008',
    authDomain: 'chatapp-86008.firebaseapp.com',
    storageBucket: 'chatapp-86008.firebasestorage.app',
  );
}
